GRID_WIDTH = 20
GRID_HEIGHT = 20

CELL_EMPTY      = 0
CELL_ADRIAN     = 1
CELL_ASTROPHAGE = 2
CELL_HAIL_MARY  = 3
CELL_BLIP_A     = 4
CELL_BEETLE     = 5
CELL_RADIATION  = 6
CELL_DEBRIS     = 7
CELL_PETROVA    = 8
CELL_GRACE      = 9

ASTROPHAGE_SPREAD_CHANCE = 0.02
ASTROPHAGE_ENERGY_DRAIN  = 5
PETROVA_ENERGY_DRAIN     = 15
ASTROPHAGE_INTENSITY_MIN = 2
ASTROPHAGE_INTENSITY_MAX = 10

RADIATION_HEALTH_DRAIN = 3

DEFAULT_TURNS    = 200
WRAP_EDGES       = True

GRACE_START_X    = 1
GRACE_START_Y    = 1
GRACE_MAX_HEALTH = 100
GRACE_MAX_ENERGY = 150

CELL_COLORS = {
    CELL_EMPTY:      "#0a0a1a",
    CELL_ADRIAN:     "#2e7d32",
    CELL_ASTROPHAGE: "#b71c1c",
    CELL_HAIL_MARY:  "#1565c0",
    CELL_BLIP_A:     "#6a1b9a",
    CELL_BEETLE:     "#f9a825",
    CELL_RADIATION:  "#e65100",
    CELL_DEBRIS:     "#4e342e",
    CELL_PETROVA:    "#880e4f",
    CELL_GRACE:      "#00e5ff",
}

CELL_LABELS = {
    CELL_EMPTY:      ".",
    CELL_ADRIAN:     "A",
    CELL_ASTROPHAGE: "*",
    CELL_HAIL_MARY:  "H",
    CELL_BLIP_A:     "B",
    CELL_BEETLE:     "b",
    CELL_RADIATION:  "R",
    CELL_DEBRIS:     "D",
    CELL_PETROVA:    "P",
    CELL_GRACE:      "G",
}
